const vinyls = [
    {
        id: 0,
        name: "Eddie Murphy: Comedian",
        artist: "Eddie Murphy",
        price: 10.00,
        instock: 10,
        description: "Eddie Murphy Comedian LP (1983) 12” Vinyl Record Album ",
        genre: "Comedy",
        imgSrc: "./img/eddie.png",
    },
    {
        id: 1,
        name: "Death Grips",
        artist: "Death Grips",
        price: 25.99,
        instock: 11,
        description: "Death Grips Record Store Day Exclusive 12” White Vinyl (2019)",
        genre: "Hip-Hop",
        imgSrc: "./img/grips.png",
    },
    {
        id: 2,
        name: "Shake it Up",
        artist: "The Cars",
        price: 15.99,
        instock: 7,
        description: "Shake it Up (1981) 12” Vinyl",
        genre: "Classic Rock",
        imgSrc: "./img/shakeitup.png",
    },
    {
        id: 3,
        name: "Rage Against the Machine",
        artist:"Rage Against the Machine",
        price: 25.99,
        instock: 5,
        description: "Rage Against the Machine (1992) self titled debut album 12” vinyl",
        genre: "Hard Rock",
        imgSrc: "./img/ratm.png",
    },
    {
        id: 4,
        name: "Fistful of Metal",
        artist: "Anthrax",
        price: 25.99,
        instock: 2,
        description: "Anthrax's debut album (1992) 12” vinyl",
        genre: "Metal",
        imgSrc: "./img/anthrax.png",
    },
    {
        id: 5,
        name: "Suffer",
        artist: "Bad Religion",
        price: 25.99,
        instock: 2,
        description: "Suffer by Bad Religion (1988) on 12” vinyl",
        genre: "Punk",
        imgSrc: "./img/suffer.png",
    },
]